// src/data/reportData.js

export const reportData = [
  {
    id: 1,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Resolucion",
  },
  {
    id: 2,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 3,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 4,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 5,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Constancia",
  },
  {
    id: 6,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 7,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 8,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 9,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Resolucion",
  },
  {
    id: 10,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 11,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 12,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 13,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Constancia",
  },
  {
    id: 14,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 15,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 16,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 17,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Resolucion",
  },
  {
    id: 18,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 19,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 20,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 21,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Constancia",
  },
  {
    id: 22,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 23,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 24,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 25,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Resolucion",
  },
  {
    id: 26,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 27,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 28,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 29,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Constancia",
  },
  {
    id: 30,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 31,
    title: "Memoria Anual 2023",
    date: "2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  },
  {
    id: 32,
    title: "Plan de Estudios 2024",
    date: "2024-04-20",
    type: "XLSX",
    DocumentType: "Doctorado",
  },
  {
    id: 33,
    title: "Informe de Proyectos de Investigación",
    date: "2024-01-15",
    type: "PDF",
    DocumentType: "Resolucion",
  },
  {
    id: 34,
    title: "Acta de Junta Directiva",
    date: "2024-02-10",
    type: "DOCX",
    DocumentType: "Grado",
  },
  {
    id: 35,
    title: "Memoria Anual 2023",
    date:"2024-03-05",
    type: "PDF",
    DocumentType: "Titulo",
  }
];
